### ISSUE TITLE
Saving a Pattern-Candidate not possible

### ISSUE THREAD

**Issue by manuwei** [PatternAtlas/pattern-atlas-ui#120]
Even as an admin, saving a pattern candidate currently leads to an error.

**Comment by TYueksel** [comment]
Please try it again now. Make sure you have a clean start by deleting your cookies before login. And please make sure that you are using the right branches on UI and API.
If this error still happens, please provide the error message from your browsers console, because when I'm trying it, everything is working fine.

**Comment by TYueksel** [comment]
Right now it is not possible to create pattern candidates for the pattern languages Quantum Computing Patterns and Reformulated Quantum Computing Patterns. It results in a SQL error where the content of the patterns are too long:
`ERROR: value too long for type character varying(255)`)

**Comment by TYueksel** [comment]
I changed the attribute type for candidate contents from character varying(255) to jsonb (check [PR](https://github.com/PatternAtlas/pattern-atlas-content/pull/10)). Seems to be working now.
